# EnigmaIRC Server server address and port
server-address: ""
server-port: 6667

# What messages from EIRC will look like in the game
# Supports Kyori's MiniMessage (read more at https://docs.advntr.dev/minimessage/format.html)
# message-format - for user messages
# session-format - for join/leave messages
message-format: "[EIRC] <user> - <message>"
session-format: "[EIRC] <user> <status>"

# Under what name messages will be sent to other users
# Only normal text is supported (no formatting)
# Use <user> placeholder to put player's name
player-name-format: "[MC] <user>"

# What is the name of the server?
# This name will be seen by other participants in the conversation when the server is turned on/off
#
server-name : "Paper Server"

# Client encryption key
# Generate new one using real client
security-key: ""